name: "Create PR with updated CHANGES.md"

on:
  workflow_dispatch:
    inputs:
      fname_changelog:
        description: 'Changelog filename'
        required: true
        default: 'CHANGES.md'
      milestone_title:
        description: 'Milestone title'
        required: True

jobs:
  create-changelog-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install changelog
      run: |
          git clone --depth 1 --single-branch --branch jn/15-milestone-argument https://github.com/neuropoly/changelog.git
          cd changelog
          pip install .
    - name: Generate changelog
      run: |
        changelog neuropoly/spinalcordtoolbox --update --name ${{ github.event.inputs.fname_changelog }} --milestone ${{ github.event.inputs.milestone_title }}
        rm "${{ github.event.inputs.fname_changelog }}.bak"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "bot/v${{ github.event.inputs.milestone_title }}"
        commit-message  : "Update ${{ github.event.inputs.fname_changelog }} for ${{ github.event.inputs.milestone_title }} release"
        title: "Update ${{ github.event.inputs.fname_changelog }} for ${{ github.event.inputs.milestone_title }} release"
        milestone: "${{ github.event.inputs.milestone_title }}"
        body: "Automated step carried out as a part of [Creating a new release](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release) checklist."
        delete-branch: true
