on:
  workflow_dispatch:
    inputs:
      fname_changelog:
        description: 'Changelog filename'
        required: true
        default: 'CHANGES.md'

jobs:
  create-changelog-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install changelog
      run: pip install changelog-neuropoly
    - name: Generate changelog
      run: changelog neuropoly/spinalcordtoolbox --update --name ${{ github.event.inputs.fname_changelog }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3