name: "Create release"

on:
  workflow_dispatch:
    inputs:
      milestone_title:
        description: 'Milestone title'
        required: true

env:
  MAIN_BRANCH: "master"
  RELEASE_BRANCH: "release"

jobs:
  create-changelog-PR:
    runs-on: ubuntu-latest
    steps:

    ################## SKIP THIS STEP ON SPINALCORDTOOLBOX ###################
    - name: "Checkout '${{ github.event.repository.name }}'"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.MAIN_BRANCH }}
        path: ${{ github.event.repository.name }}
    ##########################################################################

    - name: Checkout spinalcordtoolbox (main branch)
      uses: actions/checkout@v2
      with:
        repository: spinalcordtoolbox/spinalcordtoolbox
        fetch-depth: 0
        ref: ${{ env.MAIN_BRANCH }}
        path: spinalcordtoolbox

    - name: Install spinalcordtoolbox
      run: |
        cd spinalcordtoolbox
        ./install_sct -iy

    - name: Checkout spinalcordtoolbox (release branch)
      run: |
        cd spinalcordtoolbox
        git checkout ${{ env.RELEASE_BRANCH }}

    - name: Update requirements-freeze.txt
      run: |
        cd spinalcordtoolbox
        source python/etc/profile.d/conda.sh
        conda activate venv_sct
        pip freeze | grep -v "-e git+" | grep -v "torch" > requirements-freeze.txt
        conda deactivate
        echo "# Platform-specific torch requirements (See SCT Issue #2745)" >> requirements-freeze.txt
        grep "torch" requirements.txt >> requirements-freeze.txt

    - name: Update version.txt
      run: |
        cd spinalcordtoolbox
        echo "${{ github.event.inputs.milestone_title }}" > spinalcordtoolbox/version.txt

    - name: Set bot user data for commits
      run: |
        cd ${{ github.event.repository.name }}
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

    - name: Merge main branch into release branch
      run: |
        cd ${{ github.event.repository.name }}
        git status
        git checkout ${{ env.RELEASE_BRANCH }}
        git status
        git merge --no-ff ${{ env.MAIN_BRANCH }}

    ################## SKIP THIS STEP ON SPINALCORDTOOLBOX ###################
    - name: "Copy files to '${{ github.event.repository.name }}' (to test releases)"
      run: |
        cat spinalcordtoolbox/requirements-freeze.txt > "${{ github.event.repository.name }}/requirements-freeze.txt"
        mkdir -p "${{ github.event.repository.name }}/spinalcordtoolbox/"
        cat spinalcordtoolbox/spinalcordtoolbox/version.txt > "${{ github.event.repository.name }}/spinalcordtoolbox/version.txt"
    ##########################################################################

    ################# MODIFY THIS STEP ON SPINALCORDTOOLBOX ##################
    - name: Commit and push
      run: |
        cd ${{ github.event.repository.name }}
        git add requirements-freeze.txt
        git commit -m "Update requirements-freeze.txt for ${{ github.event.inputs.milestone_title }}"
        git add spinalcordtoolbox/version.txt
        git commit -m "Update version.txt for ${{ github.event.inputs.milestone_title }}"
        git push
    ##########################################################################

    - name: Create dummy release scripts
      run: | 
        echo "test" > "install_sct-${{ github.event.inputs.milestone_title }}_win.bat"
        echo "test" > "install_sct-${{ github.event.inputs.milestone_title }}_linux.sh"
        echo "test" > "install_sct-${{ github.event.inputs.milestone_title }}_macos.sh"

    - uses: ncipollo/release-action@v1
      name: Create release
      with:
        commit: ${{ env.RELEASE_BRANCH }}
        tag: ${{ github.event.inputs.milestone_title }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: "${{ github.event.repository.name }}/.github/workflows/release-body.md"
        artifacts: >
          "install_sct-${{ github.event.inputs.milestone_title }}_win.bat",
          "install_sct-${{ github.event.inputs.milestone_title }}_linux.sh",
          "install_sct-${{ github.event.inputs.milestone_title }}_macos.sh"
        draft: true
