name: macOS_CI
on:
  push:
    branches:
      - master
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test_env
          python-version: "3.10"
  
      - name: 'Test steps (combined so that I dont have to conda activate in each step)'
        run: |
          echo "Activate Python 3.9 conda environment"
          conda init bash
          source /Users/runner/.bash_profile
          conda activate test_env
          echo $'\nCheck environment pre-pip install'
          conda list
          pip freeze
          # echo $'\nInstall pip as pip package'
          # python3 -m pip install -U pip
          # echo $'\nCheck environment post-pip install, pre-onnxruntime install'
          # conda list
          # pip freeze
          echo $'\nInstall onnxruntime==1.17.0 as pip package'
          python3 -m pip install onnxruntime==1.17.0
          echo $'\nCheck environment post-onnxruntime install'
          conda list
          pip freeze
