name: macOS_CI
on:
  push:
    branches:
      - master
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test_env
          python-version: "3.11"
  
      - name: 'Test steps (combined so that I dont have to conda activate in each step)'
        run: |
          echo $'\nTry to determine what pip is detecting the platform to be'
          python3 -c 'import platform; print(platform.platform())'
          echo $'\nActivate Python 3.11 conda environment'
          conda init bash
          source /Users/runner/.bash_profile
          conda activate test_env
          echo $'\nTry to determine what pip is detecting the platform to be'
          python3 -c 'import platform; print(platform.platform())'
          echo $'\nInstall onnxruntime==1.17.0 as pip package'
          SYSTEM_VERSION_COMPAT=0 python3 -m pip install --no-cache-dir "onnxruntime>=1.17.0"
